[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

[".config/foot/catppuccin-mocha.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/foot/refs/heads/main/themes/catppuccin-mocha.ini"
  refreshPeriod = "168h"

[".config/fuzzel/catppuccin-mocha-peach.ini"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/fuzzel/refs/heads/main/themes/catppuccin-mocha/peach.ini"
  refreshPeriod = "168h"

[".local/share/nvim/site/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"

